export const SHOW_PRESENT = 'SHOW_PRESENT';
export const PRESENT_VIEW_INIT = 'PRESENT_VIEW_INIT';
export const PRESENT_PREVIEW_INIT = 'PRESENT_PREVIEW_INIT';
export const PRESENT_SECRET_INIT = 'PRESENT_SECRET_INIT';
export const PRESENT_TIMER_INTERVAL_ELAPSED = 'PRESENT_TIMER_INTERVAL_ELAPSED';