export const AUTH_VALUE_CHANGED = 'AUTH_VALUE_CHANGED';
export const AUTH_SUBMIT_INIT = 'AUTH_SUBMIT_INIT';
export const AUTH_SUBMIT_SUCCESS = 'AUTH_SUBMIT_SUCCESS';
export const AUTH_SUBMIT_ERROR = 'AUTH_SUBMIT_ERROR';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
export const LOGOUT = 'LOGOUT';