export const PRESENTINPUT_VALUE_CHANGED = 'PRESENTINPUT_VALUE_CHANGED';
export const PRESENTINPUT_SUBMIT_INIT = 'PRESENTINPUT_SUBMIT_INIT';
export const PRESENTINPUT_SUBMIT_SUCCESS = 'PRESENTINPUT_SUBMIT_SUCCESS';
export const PRESENTINPUT_SUBMIT_ERROR = 'PRESENTINPUT_SUBMIT_ERROR';
export const PRESENT_COUNTER_INTERVAL_ELAPSED = 'PRESENT_COUNTER_INTERVAL_ELAPSED';
export const PRESENTINPUT_CLEAR_ERROR = 'PRESENTINPUT_CLEAR_ERROR';
export const SUBMITTING = 'SUBMITTING';