export const PRESENTINPUT_VALUE_CHANGED = 'PRESENTINPUT_VALUE_CHANGED';
export const PRESENTINPUT_SUBMIT = 'PRESENTINPUT_SUBMIT';
export const PRESENT_COUNTER_INTERVAL_ELAPSED = 'PRESENT_COUNTER_INTERVAL_ELAPSED';